### PR TITLE
remove unnecessary CAMERA permission (since built-in camera was removed)

### LINKED ISSUE #15: Question on permissions
My APK scanner got a few additional checks implemented in January, and on today's release of Delta reported:

```
! repo/chat.delta.lite_30000669.apk declares sensitive permission(s):
 android.permission.READ_CONTACTS android.permission.READ_MEDIA_IMAGES
 android.permission.READ_MEDIA_VIDEO android.permission.READ_EXTERNAL_STORAGE
 android.permission.CAMERA android.permission.ACCESS_BACKGROUND_LOCATION
 android.permission.ACCESS_COARSE_LOCATION android.permission.ACCESS_FINE_LOCATION
 android.permission.RECORD_AUDIO android.permission.REQUEST_INSTALL_PACKAGES
```

Now, some of those I thought to be clear and added them already to the app's allow list (to make the explanations visible and reduce the warning reports for the next round):

image

(please correct me should I've gotten something wrong there), but a few "chocolate entries" are still open. Could you please clarify what the location permissions are needed for – and what packages Delta tries to install? Be welcome to include explanations for the others as well to make them transparent, too :wink:

As for the `DEPENDENCY_INFO_BLOCK`, that should be easy to get rid of:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

Thanks in advance!

### PR DESCRIPTION
**Pull request by adbenitez**
also tweak build.gradle to avoid unnecessary metadata

solve #15

### CODE REVIEW

**Comment by adbenitez** [comment]
cc @IzzySoft

**Comment by IzzySoft** [comment]
Scanning `deltalab-armeabi-v7a-debug-1.43.0.apk`, the `CAMERA` permission is still there:

```
Offending libs:
---------------
* Mapbox Android SDK (/com/mapbox): NonFreeComp

1 offenders.

Dangerous flags:
----------------
* debuggable

Permissions:
------------
* android.permission.READ_CONTACTS
* android.permission.READ_MEDIA_IMAGES
* android.permission.READ_MEDIA_VIDEO
* android.permission.READ_EXTERNAL_STORAGE
* android.permission.WRITE_EXTERNAL_STORAGE
* android.permission.POST_NOTIFICATIONS
* android.permission.ACCESS_BACKGROUND_LOCATION
* android.permission.ACCESS_COARSE_LOCATION
* android.permission.ACCESS_FINE_LOCATION
* android.permission.RECORD_AUDIO
* android.permission.MODIFY_AUDIO_SETTINGS
* android.permission.RECEIVE_BOOT_COMPLETED
* android.permission.VIBRATE
* android.permission.ACCESS_NETWORK_STATE
* android.permission.WAKE_LOCK
* android.permission.INTERNET
* android.permission.INSTALL_SHORTCUT
* com.android.launcher.permission.INSTALL_SHORTCUT
* android.permission.ACCESS_WIFI_STATE
* android.permission.RAISED_THREAD_PRIORITY
* android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS
* android.permission.FOREGROUND_SERVICE
* android.permission.REQUEST_INSTALL_PACKAGES
* android.permission.CAMERA
* chat.delta.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION
* com.sec.android.provider.badge.permission.READ
* com.sec.android.provider.badge.permission.WRITE
* com.htc.launcher.permission.READ_SETTINGS
* com.htc.launcher.permission.UPDATE_SHORTCUT
* com.sonyericsson.home.permission.BROADCAST_BADGE
* com.sonymobile.home.permission.PROVIDER_INSERT_BADGE
* com.anddoes.launcher.permission.UPDATE_COUNT
* com.majeur.launcher.permission.UPDATE_BADGE
* com.huawei.android.launcher.permission.CHANGE_BADGE
* com.huawei.android.launcher.permission.READ_SETTINGS
* com.huawei.android.launcher.permission.WRITE_SETTINGS
* android.permission.READ_APP_BADGE
* com.oppo.launcher.permission.READ_SETTINGS
* com.oppo.launcher.permission.WRITE_SETTINGS
* me.everything.badger.permission.BADGE_COUNT_READ
* me.everything.badger.permission.BADGE_COUNT_WRITE
```

No `DEPENDENCY_INFO_BLOCK` though, but that might be due to

    Signer #1 certificate DN: C=US, O=Android, CN=Android Debug

**Comment by adbenitez** [comment]
mmmh weird, probably there is something wrong in the pull request preview APKs I don't really use them

will create a new release and see what the scanner says

**Comment by IzzySoft** [comment]
> will create a new release and see what the scanner says

Will be scanned automatically when pulled here. Results visible with the WebIf at around 7 pm UTC then. Though you can also use the scanner yourself if you wish, it's FOSS :wink: Details outlined at: [Identify modules in apps](https://android.izzysoft.de/articles/named/app-modules-2)

**Pull request merged**
